<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12">
        <v-card class="rounded-xl">
          <v-card-title class="d-flex align-center">
            <v-icon color="primary" class="mr-2">mdi-school</v-icon>
            School Profile
          </v-card-title>

          <v-card-subtitle>
            These details will be printed on question paper headers and footers.
          </v-card-subtitle>

          <v-divider class="mt-3" />

          <v-card-text>
            <v-form ref="formRef" @submit.prevent="saveProfile">
              <v-row>
                <v-col cols="12" md="12">
                  <v-row>
                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.school_name"
                        label="School Name"
                        variant="outlined"
                        density="comfortable"
                        :rules="[rules.required]"
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.academic_session"
                        label="Academic Session"
                        placeholder="2026-27"
                        variant="outlined"
                        density="comfortable"
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.school_phone"
                        label="Phone"
                        variant="outlined"
                        density="comfortable"
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.school_email"
                        label="Email"
                        variant="outlined"
                        density="comfortable"
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.principal_name"
                        label="Principal Name"
                        variant="outlined"
                        density="comfortable"
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.school_code"
                        label="School Code"
                        variant="outlined"
                        density="comfortable"
                        disabled
                        hint="School code is generated by the system and cannot be changed."
                        persistent-hint
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.affiliation_no"
                        label="Affiliation No."
                        variant="outlined"
                        density="comfortable"
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-text-field
                        v-model="form.school_website"
                        label="Website"
                        variant="outlined"
                        density="comfortable"
                      />
                    </v-col>

                    <v-col cols="12" md="4">
                      <v-file-input
                        v-model="logoFile"
                        label="School Logo"
                        variant="outlined"
                        density="comfortable"
                        prepend-icon="mdi-image"
                        accept="image/png,image/jpeg,image/jpg,image/webp"
                        show-size
                        clearable
                      />
                    </v-col>
                    
                    <v-col cols="12">
                      <v-textarea
                        v-model="form.school_address"
                        label="School Address"
                        variant="outlined"
                        density="comfortable"
                        rows="3"
                      />
                    </v-col>
                  </v-row>
                </v-col>

              </v-row>


              <SchoolHeaderPreview
                class="mt-4"
                :school-name="form.school_name"
                :school-address="form.school_address"
                :school-phone="form.school_phone"
                :school-email="form.school_email"
                :school-logo="logoPreview"
                exam-title="Periodic Assessment 1"
                :academic-session="form.academic_session"
              />

              <v-divider class="my-4" />

              <div class="d-flex justify-end">
                <v-btn
                  color="primary"
                  size="large"
                  type="submit"
                  :loading="saving"
                  prepend-icon="mdi-content-save"
                >
                  Save School Profile
                </v-btn>
              </div>
            </v-form>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import api from '../../plugins/api'
import { useUIStore } from '../../stores/snackBar'
import SchoolHeaderPreview from '../../components/common/SchoolHeaderPreview.vue'

const ui = useUIStore()

const formRef = ref(null)
const saving = ref(false)
const logoFile = ref(null)
const existingLogoUrl = ref(null)

const form = ref({
  school_name: '',
  school_address: '',
  school_phone: '',
  school_email: '',
  academic_session: '',
  principal_name: '',
  school_code: '',
  affiliation_no: '',
  school_website: '',
})

const rules = {
  required: (value) => !!value || 'This field is required.',
}

const logoPreview = computed(() => {
  const file = Array.isArray(logoFile.value) ? logoFile.value[0] : logoFile.value

  if (file instanceof File) {
    return URL.createObjectURL(file)
  }

  return existingLogoUrl.value
})

const fetchProfile = async () => {
  try {
    const res = await api.get('/school-profile')
    const data = res.data?.data || {}

    form.value = {
      school_name: data.school_name || '',
      school_address: data.school_address || '',
      school_phone: data.school_phone || '',
      school_email: data.school_email || '',
      academic_session: data.academic_session || '',
      principal_name: data.principal_name || '',
      school_code: data.school_code || '',
      affiliation_no: data.affiliation_no || '',
      school_website: data.school_website || '',
    }

    existingLogoUrl.value = data.school_logo_url || null
  } catch (e) {
    ui.showSnackbar(
      e.response?.data?.message || 'Failed to load school profile.',
      'error'
    )
  }
}

const saveProfile = async () => {
  const result = await formRef.value?.validate()

  if (!result?.valid) return

  saving.value = true

  try {
    const payload = new FormData()

    Object.entries(form.value).forEach(([key, value]) => {
      payload.append(key, value ?? '')
    })

    const file = Array.isArray(logoFile.value) ? logoFile.value[0] : logoFile.value

    if (file instanceof File) {
      payload.append('school_logo', file)
    }

    const res = await api.post('/school-profile', payload, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    })

    ui.showSnackbar(
      res.data?.message || 'School profile updated successfully.'
    )

    logoFile.value = null
    await fetchProfile()
  } catch (e) {
    ui.showSnackbar(
      e.response?.data?.message || 'Failed to save school profile.',
      'error'
    )
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  fetchProfile()
})
</script>
